name: Destroy infrastructure (AWS, Docker Compose)

on:
  workflow_dispatch:


jobs:
  deploy-infra:
    environment: production
    runs-on: ubuntu-latest
    continue-on-error: False
    name: Destroy infrastructure (AWS, Docker Compose)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Derive SSH public key from private key for the AWS EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.OPERATOR_SSH_PRIVATE_KEY }}
        run: |
          ./scripts/store_public_private_keys.sh

      - name: Set up Terraform Version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          cd cloud_resources/aws/docker-compose
          terraform init -backend-config="bucket=${{ vars.TFSTATE_S3_BUCKET }}"

      - name: Terraform Plan
        run: |
          cd cloud_resources/aws/docker-compose
          terraform plan

      - name: Terraform Destroy
        run: |
          cd cloud_resources/aws/docker-compose
          terraform destroy -auto-approve
